name: QualityChecks
on: [ pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: QualityChecks
    steps:
    - uses: actions/checkout@v3
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"
    - name: Set up Python
      run: uv python install
    - name: Install dependencies
      run: uv sync --all-groups
    - name: Ruff lint
      run: uv run ruff check .
    - name: Ruff format
      run: uv run ruff format --check .
    - name: Mypy
      run: uv run mypy src
