name: QualityChecks
on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: QualityChecks
    steps:
    - uses: actions/checkout@v3
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"
    - name: Set up Python
      run: uv python install
    - name: Install dependencies
      run: uv sync --all-groups
    - run: |
        echo 'PR_MESSAGE<<EOF' >> $GITHUB_ENV
        uv run python meta/run.py pr_commentary >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - uses: thollander/actions-comment-pull-request@v1
      with:
        message: ${{ env.PR_MESSAGE }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        comment_includes: '# PR metrics'
