name: Testsuite

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ '3.x', 'pypy3' ]
        postgres-version: [ '9', 'latest' ]

    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pq_test
        ports:
        # will assign a random free host port
        - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install --upgrade poetry && poetry install && poetry run pytest -v --cov
      env:
        PQ_TEST_DB_PORT: ${{ job.services.postgres.ports[5432] }}
        PQ_TEST_DB_HOST: localhost
        PQ_TEST_DB_PASS: postgres
    - run: poetry run coverage report
