name: Testsuite

on:
  push:
    branches:
      - '*'
      - '!meta'
  pull_request:
    types:
      - opened

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: aq_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: [ '5432:5432' ]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - run: pip install --upgrade poetry
    - run: poetry install
    - run: poetry run pytest -v --cov
    - run: poetry run pip install psycopg2
    - run: poetry run pytest -v --engine "postgresql+psycopg2://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/aq_test"
    - run: poetry run coverage report
